"""Rogue base station / IMSI catcher detection for CellGuard.

Implements heuristics to detect fake cell towers (Stingrays, IMSI catchers)
based on the NDSS 2025 Marlin methodology and common detection techniques.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

from flyinghoneybadger.cellular.models import CellTower
from flyinghoneybadger.utils.logger import get_logger

log = get_logger("cellular.detector")

# RSSI threshold above which a tower is suspiciously strong
STRONG_SIGNAL_THRESHOLD = -50  # dBm

# Maximum expected signal change between scan cycles
MAX_SIGNAL_DELTA = 30  # dB


@dataclass
class RogueAlert:
    """An alert generated by the rogue base station detector."""

    alert_type: str
    severity: str  # "critical", "warning", "info"
    message: str
    tower: CellTower
    timestamp: datetime = field(default_factory=datetime.now)
    details: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "type": self.alert_type,
            "severity": self.severity,
            "message": self.message,
            "cell_id": self.tower.cell_id,
            "technology": self.tower.technology,
            "plmn": self.tower.plmn,
            "frequency_mhz": self.tower.frequency_mhz,
            "rssi": self.tower.rssi,
            "timestamp": self.timestamp.isoformat(),
            "details": self.details,
        }


class RogueBaseStationDetector:
    """Detects rogue base stations using multiple heuristic checks.

    Detection heuristics:
    1. Unknown Cell ID - tower not in baseline
    2. Signal Strength Anomaly - suspiciously strong signal
    3. Encryption Downgrade - tower forcing 2G/no encryption
    4. Frequency Anomaly - tower on unexpected frequency for operator
    5. LAC/TAC Change - location area changed for known cell ID
    6. Operator Mismatch - MCC/MNC doesn't match expected for that band
    7. Rapid Appearance - tower appeared suddenly between scans
    """

    def __init__(self) -> None:
        self._baseline: dict[str, CellTower] = {}
        self._previous_scan: dict[str, CellTower] = {}
        self._alerts: list[RogueAlert] = []
        self._known_plmns: set[str] = set()  # Expected operators in the area

    @property
    def alert_count(self) -> int:
        return len(self._alerts)

    def get_alerts(self) -> list[RogueAlert]:
        return self._alerts.copy()

    def load_baseline(self, towers: list[CellTower]) -> None:
        """Load known-good tower baseline for comparison."""
        self._baseline.clear()
        for tower in towers:
            self._baseline[tower.unique_id] = tower
            if tower.plmn:
                self._known_plmns.add(tower.plmn)
        log.info(
            "Loaded baseline: %d towers, %d operators",
            len(self._baseline), len(self._known_plmns),
        )

    def load_baseline_file(self, path: str) -> None:
        """Load baseline from a JSON file."""
        data = json.loads(Path(path).read_text())
        towers = []
        for entry in data.get("towers", []):
            tower = CellTower(
                cell_id=entry["cell_id"],
                technology=entry["technology"],
                mcc=entry.get("mcc", ""),
                mnc=entry.get("mnc", ""),
                lac=entry.get("lac", 0),
                tac=entry.get("tac", 0),
                arfcn=entry.get("arfcn", 0),
                earfcn=entry.get("earfcn", 0),
                frequency_mhz=entry.get("frequency_mhz", 0),
                rssi=entry.get("rssi", -120),
                band=entry.get("band", ""),
                operator=entry.get("operator", ""),
            )
            towers.append(tower)
        self.load_baseline(towers)

    def save_baseline(self, towers: list[CellTower], path: str) -> None:
        """Save current towers as baseline to a JSON file."""
        data = {
            "timestamp": datetime.now().isoformat(),
            "tower_count": len(towers),
            "towers": [
                {
                    "cell_id": t.cell_id,
                    "technology": t.technology,
                    "mcc": t.mcc,
                    "mnc": t.mnc,
                    "lac": t.lac,
                    "tac": t.tac,
                    "arfcn": t.arfcn,
                    "earfcn": t.earfcn,
                    "frequency_mhz": t.frequency_mhz,
                    "rssi": t.rssi,
                    "band": t.band,
                    "operator": t.operator,
                }
                for t in towers
            ],
        }
        Path(path).write_text(json.dumps(data, indent=2))
        log.info("Saved baseline: %d towers to %s", len(towers), path)

    def check_tower(self, tower: CellTower) -> list[RogueAlert]:
        """Check a tower against all detection heuristics.

        Args:
            tower: The cell tower to analyze.

        Returns:
            List of RogueAlert objects for any detected anomalies.
        """
        alerts = []
        alerts.extend(self._check_unknown_cell_id(tower))
        alerts.extend(self._check_signal_anomaly(tower))
        alerts.extend(self._check_encryption_downgrade(tower))
        alerts.extend(self._check_frequency_anomaly(tower))
        alerts.extend(self._check_lac_tac_change(tower))
        alerts.extend(self._check_operator_mismatch(tower))
        alerts.extend(self._check_rapid_appearance(tower))

        self._alerts.extend(alerts)
        return alerts

    def update_previous_scan(self, towers: list[CellTower]) -> None:
        """Update the previous scan reference for temporal checks."""
        self._previous_scan = {t.unique_id: t for t in towers}

    # --- Detection heuristics ---

    def _check_unknown_cell_id(self, tower: CellTower) -> list[RogueAlert]:
        """Heuristic 1: Tower not in baseline database."""
        if not self._baseline:
            return []

        if tower.unique_id not in self._baseline:
            return [RogueAlert(
                alert_type="unknown_cell",
                severity="warning",
                message=(
                    f"Unknown {tower.technology} tower: CID={tower.cell_id} "
                    f"{tower.plmn} ({tower.operator or 'Unknown'}) "
                    f"on {tower.frequency_mhz:.1f} MHz"
                ),
                tower=tower,
            )]
        return []

    def _check_signal_anomaly(self, tower: CellTower) -> list[RogueAlert]:
        """Heuristic 2: Suspiciously strong signal."""
        alerts = []

        if tower.rssi > STRONG_SIGNAL_THRESHOLD:
            alerts.append(RogueAlert(
                alert_type="strong_signal",
                severity="warning",
                message=(
                    f"Unusually strong signal from {tower.technology} tower "
                    f"CID={tower.cell_id}: {tower.rssi} dBm "
                    f"(threshold: {STRONG_SIGNAL_THRESHOLD} dBm)"
                ),
                tower=tower,
                details={"rssi": tower.rssi, "threshold": STRONG_SIGNAL_THRESHOLD},
            ))

        # Check for sudden signal increase vs previous scan
        if tower.unique_id in self._previous_scan:
            prev = self._previous_scan[tower.unique_id]
            delta = tower.rssi - prev.rssi
            if delta > MAX_SIGNAL_DELTA:
                alerts.append(RogueAlert(
                    alert_type="signal_jump",
                    severity="critical",
                    message=(
                        f"Sudden signal increase on {tower.technology} "
                        f"CID={tower.cell_id}: {prev.rssi} -> {tower.rssi} dBm "
                        f"(+{delta} dB)"
                    ),
                    tower=tower,
                    details={"previous_rssi": prev.rssi, "delta": delta},
                ))

        return alerts

    def _check_encryption_downgrade(self, tower: CellTower) -> list[RogueAlert]:
        """Heuristic 3: Tower forcing 2G / no encryption.

        A common IMSI catcher technique is to broadcast as a 2G-only tower
        since GSM A5/1 encryption is broken, allowing interception.
        """
        # If we see a GSM tower in an area where the operator also has LTE,
        # and the GSM tower is unusually strong, it could be a downgrade attack
        if tower.technology == "GSM" and tower.rssi > STRONG_SIGNAL_THRESHOLD:
            # Check if operator also has LTE towers in baseline
            has_lte = any(
                t.technology == "LTE" and t.plmn == tower.plmn
                for t in self._baseline.values()
            )
            if has_lte:
                return [RogueAlert(
                    alert_type="encryption_downgrade",
                    severity="critical",
                    message=(
                        f"Potential downgrade attack: Strong GSM tower "
                        f"CID={tower.cell_id} ({tower.operator}) at "
                        f"{tower.rssi} dBm — operator has LTE in area"
                    ),
                    tower=tower,
                )]
        return []

    def _check_frequency_anomaly(self, tower: CellTower) -> list[RogueAlert]:
        """Heuristic 4: Tower on unexpected frequency for operator."""
        if not self._baseline or not tower.plmn:
            return []

        # Get expected frequencies for this operator from baseline
        expected_freqs = set()
        for baseline_tower in self._baseline.values():
            if baseline_tower.plmn == tower.plmn and baseline_tower.technology == tower.technology:
                expected_freqs.add(baseline_tower.band)

        if expected_freqs and tower.band and tower.band not in expected_freqs:
            return [RogueAlert(
                alert_type="frequency_anomaly",
                severity="warning",
                message=(
                    f"{tower.technology} tower CID={tower.cell_id} "
                    f"({tower.operator}) on unexpected band {tower.band} "
                    f"(expected: {', '.join(sorted(expected_freqs))})"
                ),
                tower=tower,
                details={"expected_bands": sorted(expected_freqs)},
            )]
        return []

    def _check_lac_tac_change(self, tower: CellTower) -> list[RogueAlert]:
        """Heuristic 5: Location area changed for known cell ID."""
        if not self._baseline:
            return []

        for baseline_tower in self._baseline.values():
            if (baseline_tower.cell_id == tower.cell_id
                    and baseline_tower.technology == tower.technology
                    and baseline_tower.plmn == tower.plmn):

                if tower.technology == "GSM" and tower.lac != baseline_tower.lac and baseline_tower.lac > 0:
                    return [RogueAlert(
                        alert_type="lac_change",
                        severity="critical",
                        message=(
                            f"LAC changed for GSM CID={tower.cell_id}: "
                            f"{baseline_tower.lac} -> {tower.lac}"
                        ),
                        tower=tower,
                        details={"baseline_lac": baseline_tower.lac},
                    )]

                if tower.technology == "LTE" and tower.tac != baseline_tower.tac and baseline_tower.tac > 0:
                    return [RogueAlert(
                        alert_type="tac_change",
                        severity="critical",
                        message=(
                            f"TAC changed for LTE PCI={tower.pci}: "
                            f"{baseline_tower.tac} -> {tower.tac}"
                        ),
                        tower=tower,
                        details={"baseline_tac": baseline_tower.tac},
                    )]
        return []

    def _check_operator_mismatch(self, tower: CellTower) -> list[RogueAlert]:
        """Heuristic 6: MCC/MNC doesn't match expected operators."""
        if not self._known_plmns or not tower.plmn:
            return []

        if tower.plmn not in self._known_plmns:
            return [RogueAlert(
                alert_type="operator_mismatch",
                severity="warning",
                message=(
                    f"Unknown operator {tower.plmn} ({tower.operator or '?'}) "
                    f"on {tower.technology} CID={tower.cell_id} — "
                    f"not in baseline operators"
                ),
                tower=tower,
                details={"known_plmns": sorted(self._known_plmns)},
            )]
        return []

    def _check_rapid_appearance(self, tower: CellTower) -> list[RogueAlert]:
        """Heuristic 7: Tower appeared suddenly between scans."""
        if not self._previous_scan or not self._baseline:
            return []

        # Tower wasn't in previous scan AND isn't in baseline
        if (tower.unique_id not in self._previous_scan
                and tower.unique_id not in self._baseline):
            return [RogueAlert(
                alert_type="rapid_appearance",
                severity="warning",
                message=(
                    f"New {tower.technology} tower appeared: CID={tower.cell_id} "
                    f"{tower.plmn} ({tower.operator or 'Unknown'}) "
                    f"at {tower.rssi} dBm"
                ),
                tower=tower,
            )]
        return []
